train_dataset_path = '/Users/namai/Documents/GitHub/Image/dataset/train/'
test_dataset_path = '/Users/namai/Documents/GitHub/Image/dataset/test'
validation_dataset_path = '/Users/namai/Documents/GitHub/Image/dataset/validation'
train_csv_file = 'train.csv'
apple_banana_csv_file = 'apple_banana.csv'